#!/usr/bin/env python3
"""Regenerate Sources/IndicatorsCore/PricingData.swift from LiteLLM's public pricing table.

Usage: python3 scripts/update-pricing.py [path-to-litellm-json]
Without an argument the script downloads the latest table from GitHub.
"""
import json, sys, urllib.request, datetime, pathlib

URL = "https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json"
PROVIDERS = {"anthropic", "openai", "gemini", "xai"}
FIELDS = [
    ("input_cost_per_token", "input"),
    ("output_cost_per_token", "output"),
    ("cache_read_input_token_cost", "cacheRead"),
    ("cache_creation_input_token_cost", "cacheWrite"),
    ("cache_creation_input_token_cost_above_1hr", "cacheWrite1h"),
]

def load(path):
    if path:
        return json.load(open(path))
    with urllib.request.urlopen(URL, timeout=30) as r:
        return json.load(r)

def main():
    src = load(sys.argv[1] if len(sys.argv) > 1 else None)
    out = {}
    for key, v in src.items():
        if not isinstance(v, dict) or v.get("litellm_provider") not in PROVIDERS:
            continue
        if v.get("mode") not in ("chat", "responses"):
            continue
        if v.get("input_cost_per_token") is None or v.get("output_cost_per_token") is None:
            continue
        name = key.split("/", 1)[1] if "/" in key else key
        entry = {"provider": v["litellm_provider"]}
        for src_field, dst in FIELDS:
            if v.get(src_field) is not None:
                entry[dst] = v[src_field]
        out.setdefault(name, entry)
    root = pathlib.Path(__file__).resolve().parent.parent
    target = root / "Sources/IndicatorsCore/PricingData.swift"
    today = datetime.date.today().isoformat()
    body = json.dumps(dict(sorted(out.items())), separators=(",", ":"), sort_keys=True)
    target.write_text(
        "// Generated by scripts/update-pricing.py on %s. Do not edit by hand.\n"
        "// Source: %s\n\n"
        "enum PricingData {\n"
        "    static let generatedOn = \"%s\"\n"
        "    static let json = #\"\"\"\n%s\n\"\"\"#\n"
        "}\n" % (today, URL, today, body)
    )
    print(f"wrote {target} with {len(out)} models")

if __name__ == "__main__":
    main()
